---
name: Molecule Test

"on":
  push:
    branches:
      - main
    paths:
      - "roles/**"

jobs:
  find-molecule:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get changhed roles
        id: changed-roles
        uses: tj-actions/changed-files@v35
        with:
          path: "roles"
          diff_relative: "true"
          files: "**"
          dir_names: "true"
          dir_names_max_depth: "1"
          since_last_remote_commit: "true"
        
      - name: Return roles that have molecule tests
        id: matrix
        run: |
          roles=""
          for role in ${{ steps.changed-roles.outputs.all_changed_and_modified_files }}; do
            if [ -f roles/$role/molecule/default/molecule.yml ]; then
              roles='$roles\"$role\", '
            fi
          done
          echo "::set-output name=value::[$roles]"


  molecule:
    runs-on: ubuntu-latest
    needs: 
      - find-molecule
    strategy:
      matrix:
        role: ${{ fromJson(needs.find-molecule.outputs.matrix) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies.
        working-directory: roles/${{ matrix.role }}
        run: pip3 install -r requirements.txt

      - name: Install Galaxy dependencies.
        working-directory: roles/${{ matrix.role }}
        run: ansible-galaxy collection install community.docker

      - name: Run molecule
        working-directory: roles/${{ matrix.role }}
        run: "molecule test"

...
